// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Av4JhG/system-monitoring/internal/sm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCPUInterface creates a new instance of MockCPUInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCPUInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCPUInterface {
	mock := &MockCPUInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCPUInterface is an autogenerated mock type for the CPUInterface type
type MockCPUInterface struct {
	mock.Mock
}

type MockCPUInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCPUInterface) EXPECT() *MockCPUInterface_Expecter {
	return &MockCPUInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCPUInterface
func (_mock *MockCPUInterface) Execute(ctx context.Context, action sm.MetricCommand) (*sm.CPUData, error) {
	ret := _mock.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *sm.CPUData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) (*sm.CPUData, error)); ok {
		return returnFunc(ctx, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) *sm.CPUData); ok {
		r0 = returnFunc(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sm.CPUData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sm.MetricCommand) error); ok {
		r1 = returnFunc(ctx, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCPUInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCPUInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - action sm.MetricCommand
func (_e *MockCPUInterface_Expecter) Execute(ctx interface{}, action interface{}) *MockCPUInterface_Execute_Call {
	return &MockCPUInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, action)}
}

func (_c *MockCPUInterface_Execute_Call) Run(run func(ctx context.Context, action sm.MetricCommand)) *MockCPUInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sm.MetricCommand
		if args[1] != nil {
			arg1 = args[1].(sm.MetricCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCPUInterface_Execute_Call) Return(cPUData *sm.CPUData, err error) *MockCPUInterface_Execute_Call {
	_c.Call.Return(cPUData, err)
	return _c
}

func (_c *MockCPUInterface_Execute_Call) RunAndReturn(run func(ctx context.Context, action sm.MetricCommand) (*sm.CPUData, error)) *MockCPUInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadAvgInterface creates a new instance of MockLoadAvgInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadAvgInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadAvgInterface {
	mock := &MockLoadAvgInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadAvgInterface is an autogenerated mock type for the LoadAvgInterface type
type MockLoadAvgInterface struct {
	mock.Mock
}

type MockLoadAvgInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadAvgInterface) EXPECT() *MockLoadAvgInterface_Expecter {
	return &MockLoadAvgInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockLoadAvgInterface
func (_mock *MockLoadAvgInterface) Execute(ctx context.Context) (*sm.LoadAvgData, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *sm.LoadAvgData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*sm.LoadAvgData, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *sm.LoadAvgData); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sm.LoadAvgData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoadAvgInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLoadAvgInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoadAvgInterface_Expecter) Execute(ctx interface{}) *MockLoadAvgInterface_Execute_Call {
	return &MockLoadAvgInterface_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockLoadAvgInterface_Execute_Call) Run(run func(ctx context.Context)) *MockLoadAvgInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoadAvgInterface_Execute_Call) Return(loadAvgData *sm.LoadAvgData, err error) *MockLoadAvgInterface_Execute_Call {
	_c.Call.Return(loadAvgData, err)
	return _c
}

func (_c *MockLoadAvgInterface_Execute_Call) RunAndReturn(run func(ctx context.Context) (*sm.LoadAvgData, error)) *MockLoadAvgInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadDisksInterface creates a new instance of MockLoadDisksInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadDisksInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadDisksInterface {
	mock := &MockLoadDisksInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadDisksInterface is an autogenerated mock type for the LoadDisksInterface type
type MockLoadDisksInterface struct {
	mock.Mock
}

type MockLoadDisksInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadDisksInterface) EXPECT() *MockLoadDisksInterface_Expecter {
	return &MockLoadDisksInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockLoadDisksInterface
func (_mock *MockLoadDisksInterface) Execute(ctx context.Context, action sm.MetricCommand) (sm.LoadDisksData, error) {
	ret := _mock.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 sm.LoadDisksData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) (sm.LoadDisksData, error)); ok {
		return returnFunc(ctx, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) sm.LoadDisksData); ok {
		r0 = returnFunc(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sm.LoadDisksData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sm.MetricCommand) error); ok {
		r1 = returnFunc(ctx, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoadDisksInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLoadDisksInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - action sm.MetricCommand
func (_e *MockLoadDisksInterface_Expecter) Execute(ctx interface{}, action interface{}) *MockLoadDisksInterface_Execute_Call {
	return &MockLoadDisksInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, action)}
}

func (_c *MockLoadDisksInterface_Execute_Call) Run(run func(ctx context.Context, action sm.MetricCommand)) *MockLoadDisksInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sm.MetricCommand
		if args[1] != nil {
			arg1 = args[1].(sm.MetricCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadDisksInterface_Execute_Call) Return(loadDisksData sm.LoadDisksData, err error) *MockLoadDisksInterface_Execute_Call {
	_c.Call.Return(loadDisksData, err)
	return _c
}

func (_c *MockLoadDisksInterface_Execute_Call) RunAndReturn(run func(ctx context.Context, action sm.MetricCommand) (sm.LoadDisksData, error)) *MockLoadDisksInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollector creates a new instance of MockCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollector {
	mock := &MockCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollector is an autogenerated mock type for the Collector type
type MockCollector struct {
	mock.Mock
}

type MockCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollector) EXPECT() *MockCollector_Expecter {
	return &MockCollector_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockCollector
func (_mock *MockCollector) Start(context1 context.Context, metricCollectors sm.MetricCollectors, metricsDataCh chan<- sm.MetricsData) {
	_mock.Called(context1, metricCollectors, metricsDataCh)
	return
}

// MockCollector_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCollector_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
//   - metricCollectors sm.MetricCollectors
//   - metricsDataCh chan<- sm.MetricsData
func (_e *MockCollector_Expecter) Start(context1 interface{}, metricCollectors interface{}, metricsDataCh interface{}) *MockCollector_Start_Call {
	return &MockCollector_Start_Call{Call: _e.mock.On("Start", context1, metricCollectors, metricsDataCh)}
}

func (_c *MockCollector_Start_Call) Run(run func(context1 context.Context, metricCollectors sm.MetricCollectors, metricsDataCh chan<- sm.MetricsData)) *MockCollector_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sm.MetricCollectors
		if args[1] != nil {
			arg1 = args[1].(sm.MetricCollectors)
		}
		var arg2 chan<- sm.MetricsData
		if args[2] != nil {
			arg2 = args[2].(chan<- sm.MetricsData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollector_Start_Call) Return() *MockCollector_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCollector_Start_Call) RunAndReturn(run func(context1 context.Context, metricCollectors sm.MetricCollectors, metricsDataCh chan<- sm.MetricsData)) *MockCollector_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockCollector
func (_mock *MockCollector) Stop(context1 context.Context) {
	_mock.Called(context1)
	return
}

// MockCollector_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCollector_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockCollector_Expecter) Stop(context1 interface{}) *MockCollector_Stop_Call {
	return &MockCollector_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockCollector_Stop_Call) Run(run func(context1 context.Context)) *MockCollector_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollector_Stop_Call) Return() *MockCollector_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCollector_Stop_Call) RunAndReturn(run func(context1 context.Context)) *MockCollector_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockNewClienter creates a new instance of MockNewClienter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNewClienter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNewClienter {
	mock := &MockNewClienter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNewClienter is an autogenerated mock type for the NewClienter type
type MockNewClienter struct {
	mock.Mock
}

type MockNewClienter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNewClienter) EXPECT() *MockNewClienter_Expecter {
	return &MockNewClienter_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockNewClienter
func (_mock *MockNewClienter) NewClient(clientData sm.ClientData) (<-chan *sm.Stats, func(), error) {
	ret := _mock.Called(clientData)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 <-chan *sm.Stats
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(sm.ClientData) (<-chan *sm.Stats, func(), error)); ok {
		return returnFunc(clientData)
	}
	if returnFunc, ok := ret.Get(0).(func(sm.ClientData) <-chan *sm.Stats); ok {
		r0 = returnFunc(clientData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sm.Stats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sm.ClientData) func()); ok {
		r1 = returnFunc(clientData)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(sm.ClientData) error); ok {
		r2 = returnFunc(clientData)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNewClienter_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockNewClienter_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - clientData sm.ClientData
func (_e *MockNewClienter_Expecter) NewClient(clientData interface{}) *MockNewClienter_NewClient_Call {
	return &MockNewClienter_NewClient_Call{Call: _e.mock.On("NewClient", clientData)}
}

func (_c *MockNewClienter_NewClient_Call) Run(run func(clientData sm.ClientData)) *MockNewClienter_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sm.ClientData
		if args[0] != nil {
			arg0 = args[0].(sm.ClientData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNewClienter_NewClient_Call) Return(statsCh <-chan *sm.Stats, fn func(), err error) *MockNewClienter_NewClient_Call {
	_c.Call.Return(statsCh, fn, err)
	return _c
}

func (_c *MockNewClienter_NewClient_Call) RunAndReturn(run func(clientData sm.ClientData) (<-chan *sm.Stats, func(), error)) *MockNewClienter_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClients creates a new instance of MockClients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClients(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClients {
	mock := &MockClients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClients is an autogenerated mock type for the Clients type
type MockClients struct {
	mock.Mock
}

type MockClients_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClients) EXPECT() *MockClients_Expecter {
	return &MockClients_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockClients
func (_mock *MockClients) NewClient(clientData sm.ClientData) (<-chan *sm.Stats, func(), error) {
	ret := _mock.Called(clientData)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 <-chan *sm.Stats
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(sm.ClientData) (<-chan *sm.Stats, func(), error)); ok {
		return returnFunc(clientData)
	}
	if returnFunc, ok := ret.Get(0).(func(sm.ClientData) <-chan *sm.Stats); ok {
		r0 = returnFunc(clientData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sm.Stats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sm.ClientData) func()); ok {
		r1 = returnFunc(clientData)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(sm.ClientData) error); ok {
		r2 = returnFunc(clientData)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClients_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockClients_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - clientData sm.ClientData
func (_e *MockClients_Expecter) NewClient(clientData interface{}) *MockClients_NewClient_Call {
	return &MockClients_NewClient_Call{Call: _e.mock.On("NewClient", clientData)}
}

func (_c *MockClients_NewClient_Call) Run(run func(clientData sm.ClientData)) *MockClients_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sm.ClientData
		if args[0] != nil {
			arg0 = args[0].(sm.ClientData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClients_NewClient_Call) Return(statsCh <-chan *sm.Stats, fn func(), err error) *MockClients_NewClient_Call {
	_c.Call.Return(statsCh, fn, err)
	return _c
}

func (_c *MockClients_NewClient_Call) RunAndReturn(run func(clientData sm.ClientData) (<-chan *sm.Stats, func(), error)) *MockClients_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockClients
func (_mock *MockClients) Start(context1 context.Context, metricsDataCh <-chan sm.MetricsData) {
	_mock.Called(context1, metricsDataCh)
	return
}

// MockClients_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClients_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
//   - metricsDataCh <-chan sm.MetricsData
func (_e *MockClients_Expecter) Start(context1 interface{}, metricsDataCh interface{}) *MockClients_Start_Call {
	return &MockClients_Start_Call{Call: _e.mock.On("Start", context1, metricsDataCh)}
}

func (_c *MockClients_Start_Call) Run(run func(context1 context.Context, metricsDataCh <-chan sm.MetricsData)) *MockClients_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan sm.MetricsData
		if args[1] != nil {
			arg1 = args[1].(<-chan sm.MetricsData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClients_Start_Call) Return() *MockClients_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClients_Start_Call) RunAndReturn(run func(context1 context.Context, metricsDataCh <-chan sm.MetricsData)) *MockClients_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockClients
func (_mock *MockClients) Stop(context1 context.Context) {
	_mock.Called(context1)
	return
}

// MockClients_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockClients_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockClients_Expecter) Stop(context1 interface{}) *MockClients_Stop_Call {
	return &MockClients_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockClients_Stop_Call) Run(run func(context1 context.Context)) *MockClients_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClients_Stop_Call) Return() *MockClients_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClients_Stop_Call) RunAndReturn(run func(context1 context.Context)) *MockClients_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockGRPCServer creates a new instance of MockGRPCServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCServer {
	mock := &MockGRPCServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCServer is an autogenerated mock type for the GRPCServer type
type MockGRPCServer struct {
	mock.Mock
}

type MockGRPCServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCServer) EXPECT() *MockGRPCServer_Expecter {
	return &MockGRPCServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockGRPCServer
func (_mock *MockGRPCServer) Start(addr string, clients sm.NewClienter) error {
	ret := _mock.Called(addr, clients)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, sm.NewClienter) error); ok {
		r0 = returnFunc(addr, clients)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGRPCServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockGRPCServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - addr string
//   - clients sm.NewClienter
func (_e *MockGRPCServer_Expecter) Start(addr interface{}, clients interface{}) *MockGRPCServer_Start_Call {
	return &MockGRPCServer_Start_Call{Call: _e.mock.On("Start", addr, clients)}
}

func (_c *MockGRPCServer_Start_Call) Run(run func(addr string, clients sm.NewClienter)) *MockGRPCServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 sm.NewClienter
		if args[1] != nil {
			arg1 = args[1].(sm.NewClienter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGRPCServer_Start_Call) Return(err error) *MockGRPCServer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGRPCServer_Start_Call) RunAndReturn(run func(addr string, clients sm.NewClienter) error) *MockGRPCServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockGRPCServer
func (_mock *MockGRPCServer) Stop(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockGRPCServer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockGRPCServer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGRPCServer_Expecter) Stop(ctx interface{}) *MockGRPCServer_Stop_Call {
	return &MockGRPCServer_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockGRPCServer_Stop_Call) Run(run func(ctx context.Context)) *MockGRPCServer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGRPCServer_Stop_Call) Return() *MockGRPCServer_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGRPCServer_Stop_Call) RunAndReturn(run func(ctx context.Context)) *MockGRPCServer_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debug(msg interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, args ...interface{})) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, args ...interface{})) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Error(msg interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, args ...interface{})) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, args ...interface{})) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Info(msg interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, args ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// NewMockUsedFSInterface creates a new instance of MockUsedFSInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsedFSInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsedFSInterface {
	mock := &MockUsedFSInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsedFSInterface is an autogenerated mock type for the UsedFSInterface type
type MockUsedFSInterface struct {
	mock.Mock
}

type MockUsedFSInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsedFSInterface) EXPECT() *MockUsedFSInterface_Expecter {
	return &MockUsedFSInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUsedFSInterface
func (_mock *MockUsedFSInterface) Execute(ctx context.Context, action sm.MetricCommand) (sm.UsedFSData, error) {
	ret := _mock.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 sm.UsedFSData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) (sm.UsedFSData, error)); ok {
		return returnFunc(ctx, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sm.MetricCommand) sm.UsedFSData); ok {
		r0 = returnFunc(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sm.UsedFSData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sm.MetricCommand) error); ok {
		r1 = returnFunc(ctx, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsedFSInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUsedFSInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - action sm.MetricCommand
func (_e *MockUsedFSInterface_Expecter) Execute(ctx interface{}, action interface{}) *MockUsedFSInterface_Execute_Call {
	return &MockUsedFSInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, action)}
}

func (_c *MockUsedFSInterface_Execute_Call) Run(run func(ctx context.Context, action sm.MetricCommand)) *MockUsedFSInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sm.MetricCommand
		if args[1] != nil {
			arg1 = args[1].(sm.MetricCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsedFSInterface_Execute_Call) Return(usedFSData sm.UsedFSData, err error) *MockUsedFSInterface_Execute_Call {
	_c.Call.Return(usedFSData, err)
	return _c
}

func (_c *MockUsedFSInterface_Execute_Call) RunAndReturn(run func(ctx context.Context, action sm.MetricCommand) (sm.UsedFSData, error)) *MockUsedFSInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}
