version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    # - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    funlen:
      lines: 150
      statements: 80
    gosec:
      excludes:
        - G115
    depguard:
      rules:
        main:
          allow:
            - fmt
            - time
            - context
            - bufio
            - errors
            - flag
            - io
            - log
            - math/rand
            - os
            - os/exec
            - sync
            - net
            - github.com/spf13/viper
            - gopkg.in/natefinch/lumberjack.v2
            - google.golang.org/grpc
            - google.golang.org/grpc/credentials/insecure
            - google.golang.org/grpc/codes
            - google.golang.org/grpc/status
            - google.golang.org/protobuf/types/known/timestamppb
            - github.com/Av4JhG/system-monitoring/pb
            - github.com/Av4JhG/system-monitoring/internal/sm
            - github.com/Av4JhG/system-monitoring/config
            
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
