app:
  maxSeconds: 600

metric:
  cpu: true
  loadAvg: true
  loadDisk: true
  usedFs: true
  topTalkersNetwork: true
  networkStat: true

log:
  level: "info"
  file: "app.log"
    
server:
  host: "localhost"
  port: 8000