// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/sm.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadAvg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float64                `protobuf:"fixed64,1,opt,name=Load1,proto3" json:"Load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,2,opt,name=Load5,proto3" json:"Load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,3,opt,name=Load15,proto3" json:"Load15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAvg) Reset() {
	*x = LoadAvg{}
	mi := &file_proto_sm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvg) ProtoMessage() {}

func (x *LoadAvg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvg.ProtoReflect.Descriptor instead.
func (*LoadAvg) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{0}
}

func (x *LoadAvg) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *LoadAvg) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *LoadAvg) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          float64                `protobuf:"fixed64,1,opt,name=User,proto3" json:"User,omitempty"`
	System        float64                `protobuf:"fixed64,2,opt,name=System,proto3" json:"System,omitempty"`
	Idle          float64                `protobuf:"fixed64,3,opt,name=Idle,proto3" json:"Idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_proto_sm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{1}
}

func (x *CPU) GetUser() float64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CPU) GetSystem() float64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CPU) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type LoadDisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Tps           float64                `protobuf:"fixed64,2,opt,name=Tps,proto3" json:"Tps,omitempty"`
	KBRead        float64                `protobuf:"fixed64,3,opt,name=KBRead,proto3" json:"KBRead,omitempty"`
	KBWrite       float64                `protobuf:"fixed64,4,opt,name=KBWrite,proto3" json:"KBWrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDisk) Reset() {
	*x = LoadDisk{}
	mi := &file_proto_sm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDisk) ProtoMessage() {}

func (x *LoadDisk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDisk.ProtoReflect.Descriptor instead.
func (*LoadDisk) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{2}
}

func (x *LoadDisk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadDisk) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *LoadDisk) GetKBRead() float64 {
	if x != nil {
		return x.KBRead
	}
	return 0
}

func (x *LoadDisk) GetKBWrite() float64 {
	if x != nil {
		return x.KBWrite
	}
	return 0
}

type UsedFS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	UsedSpace     float64                `protobuf:"fixed64,2,opt,name=UsedSpace,proto3" json:"UsedSpace,omitempty"`
	UsedInode     float64                `protobuf:"fixed64,3,opt,name=UsedInode,proto3" json:"UsedInode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsedFS) Reset() {
	*x = UsedFS{}
	mi := &file_proto_sm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsedFS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsedFS) ProtoMessage() {}

func (x *UsedFS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsedFS.ProtoReflect.Descriptor instead.
func (*UsedFS) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{3}
}

func (x *UsedFS) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UsedFS) GetUsedSpace() float64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *UsedFS) GetUsedInode() float64 {
	if x != nil {
		return x.UsedInode
	}
	return 0
}

type SystemStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	LoadAvg       *LoadAvg               `protobuf:"bytes,2,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	Cpu           *CPU                   `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	LoadDisks     []*LoadDisk            `protobuf:"bytes,4,rep,name=load_disks,json=loadDisks,proto3" json:"load_disks,omitempty"`
	UsedFs        []*UsedFS              `protobuf:"bytes,5,rep,name=used_fs,json=usedFs,proto3" json:"used_fs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatistics) Reset() {
	*x = SystemStatistics{}
	mi := &file_proto_sm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatistics) ProtoMessage() {}

func (x *SystemStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatistics.ProtoReflect.Descriptor instead.
func (*SystemStatistics) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{4}
}

func (x *SystemStatistics) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SystemStatistics) GetLoadAvg() *LoadAvg {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

func (x *SystemStatistics) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemStatistics) GetLoadDisks() []*LoadDisk {
	if x != nil {
		return x.LoadDisks
	}
	return nil
}

func (x *SystemStatistics) GetUsedFs() []*UsedFS {
	if x != nil {
		return x.UsedFs
	}
	return nil
}

type SystemStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	M             int32                  `protobuf:"varint,2,opt,name=M,proto3" json:"M,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatisticsRequest) Reset() {
	*x = SystemStatisticsRequest{}
	mi := &file_proto_sm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatisticsRequest) ProtoMessage() {}

func (x *SystemStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatisticsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sm_proto_rawDescGZIP(), []int{5}
}

func (x *SystemStatisticsRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *SystemStatisticsRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

var File_proto_sm_proto protoreflect.FileDescriptor

const file_proto_sm_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/sm.proto\x12\n" +
	"statistics\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\aLoadAvg\x12\x14\n" +
	"\x05Load1\x18\x01 \x01(\x01R\x05Load1\x12\x14\n" +
	"\x05Load5\x18\x02 \x01(\x01R\x05Load5\x12\x16\n" +
	"\x06Load15\x18\x03 \x01(\x01R\x06Load15\"E\n" +
	"\x03CPU\x12\x12\n" +
	"\x04User\x18\x01 \x01(\x01R\x04User\x12\x16\n" +
	"\x06System\x18\x02 \x01(\x01R\x06System\x12\x12\n" +
	"\x04Idle\x18\x03 \x01(\x01R\x04Idle\"b\n" +
	"\bLoadDisk\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Tps\x18\x02 \x01(\x01R\x03Tps\x12\x16\n" +
	"\x06KBRead\x18\x03 \x01(\x01R\x06KBRead\x12\x18\n" +
	"\aKBWrite\x18\x04 \x01(\x01R\aKBWrite\"X\n" +
	"\x06UsedFS\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\x12\x1c\n" +
	"\tUsedSpace\x18\x02 \x01(\x01R\tUsedSpace\x12\x1c\n" +
	"\tUsedInode\x18\x03 \x01(\x01R\tUsedInode\"\xf7\x01\n" +
	"\x10SystemStatistics\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\bload_avg\x18\x02 \x01(\v2\x13.statistics.LoadAvgR\aloadAvg\x12!\n" +
	"\x03cpu\x18\x03 \x01(\v2\x0f.statistics.CPUR\x03cpu\x123\n" +
	"\n" +
	"load_disks\x18\x04 \x03(\v2\x14.statistics.LoadDiskR\tloadDisks\x12+\n" +
	"\aused_fs\x18\x05 \x03(\v2\x12.statistics.UsedFSR\x06usedFs\"5\n" +
	"\x17SystemStatisticsRequest\x12\f\n" +
	"\x01N\x18\x01 \x01(\x05R\x01N\x12\f\n" +
	"\x01M\x18\x02 \x01(\x05R\x01M2W\n" +
	"\x02Sm\x12Q\n" +
	"\bGetStats\x12#.statistics.SystemStatisticsRequest\x1a\x1c.statistics.SystemStatistics\"\x000\x01B\bZ\x06.;grpcb\x06proto3"

var (
	file_proto_sm_proto_rawDescOnce sync.Once
	file_proto_sm_proto_rawDescData []byte
)

func file_proto_sm_proto_rawDescGZIP() []byte {
	file_proto_sm_proto_rawDescOnce.Do(func() {
		file_proto_sm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sm_proto_rawDesc), len(file_proto_sm_proto_rawDesc)))
	})
	return file_proto_sm_proto_rawDescData
}

var file_proto_sm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sm_proto_goTypes = []any{
	(*LoadAvg)(nil),                 // 0: statistics.LoadAvg
	(*CPU)(nil),                     // 1: statistics.CPU
	(*LoadDisk)(nil),                // 2: statistics.LoadDisk
	(*UsedFS)(nil),                  // 3: statistics.UsedFS
	(*SystemStatistics)(nil),        // 4: statistics.SystemStatistics
	(*SystemStatisticsRequest)(nil), // 5: statistics.SystemStatisticsRequest
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_proto_sm_proto_depIdxs = []int32{
	6, // 0: statistics.SystemStatistics.time:type_name -> google.protobuf.Timestamp
	0, // 1: statistics.SystemStatistics.load_avg:type_name -> statistics.LoadAvg
	1, // 2: statistics.SystemStatistics.cpu:type_name -> statistics.CPU
	2, // 3: statistics.SystemStatistics.load_disks:type_name -> statistics.LoadDisk
	3, // 4: statistics.SystemStatistics.used_fs:type_name -> statistics.UsedFS
	5, // 5: statistics.Sm.GetStats:input_type -> statistics.SystemStatisticsRequest
	4, // 6: statistics.Sm.GetStats:output_type -> statistics.SystemStatistics
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_sm_proto_init() }
func file_proto_sm_proto_init() {
	if File_proto_sm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sm_proto_rawDesc), len(file_proto_sm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sm_proto_goTypes,
		DependencyIndexes: file_proto_sm_proto_depIdxs,
		MessageInfos:      file_proto_sm_proto_msgTypes,
	}.Build()
	File_proto_sm_proto = out.File
	file_proto_sm_proto_goTypes = nil
	file_proto_sm_proto_depIdxs = nil
}
