// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/sm.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sm_GetStats_FullMethodName = "/statistics.Sm/GetStats"
)

// SmClient is the client API for Sm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmClient interface {
	GetStats(ctx context.Context, in *SystemStatisticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStatistics], error)
}

type smClient struct {
	cc grpc.ClientConnInterface
}

func NewSmClient(cc grpc.ClientConnInterface) SmClient {
	return &smClient{cc}
}

func (c *smClient) GetStats(ctx context.Context, in *SystemStatisticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStatistics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sm_ServiceDesc.Streams[0], Sm_GetStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SystemStatisticsRequest, SystemStatistics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sm_GetStatsClient = grpc.ServerStreamingClient[SystemStatistics]

// SmServer is the server API for Sm service.
// All implementations must embed UnimplementedSmServer
// for forward compatibility.
type SmServer interface {
	GetStats(*SystemStatisticsRequest, grpc.ServerStreamingServer[SystemStatistics]) error
	mustEmbedUnimplementedSmServer()
}

// UnimplementedSmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmServer struct{}

func (UnimplementedSmServer) GetStats(*SystemStatisticsRequest, grpc.ServerStreamingServer[SystemStatistics]) error {
	return status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSmServer) mustEmbedUnimplementedSmServer() {}
func (UnimplementedSmServer) testEmbeddedByValue()            {}

// UnsafeSmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmServer will
// result in compilation errors.
type UnsafeSmServer interface {
	mustEmbedUnimplementedSmServer()
}

func RegisterSmServer(s grpc.ServiceRegistrar, srv SmServer) {
	// If the following call pancis, it indicates UnimplementedSmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sm_ServiceDesc, srv)
}

func _Sm_GetStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SystemStatisticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmServer).GetStats(m, &grpc.GenericServerStream[SystemStatisticsRequest, SystemStatistics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sm_GetStatsServer = grpc.ServerStreamingServer[SystemStatistics]

// Sm_ServiceDesc is the grpc.ServiceDesc for Sm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.Sm",
	HandlerType: (*SmServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStats",
			Handler:       _Sm_GetStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sm.proto",
}
